# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-08 03:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CabInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locate', models.CharField(max_length=20, verbose_name='\u673a\u67dc\u4f4d\u7f6e')),
            ],
            options={
                'db_table': 'cabindo',
                'verbose_name': '\u673a\u67dc\u4fe1\u606f\u8868',
                'verbose_name_plural': '\u673a\u67dc\u4fe1\u606f\u8868',
            },
        ),
        migrations.CreateModel(
            name='IDCInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='\u673a\u623f\u540d\u79f0')),
                ('locate', models.CharField(max_length=100, verbose_name='\u673a\u623f\u4f4d\u7f6e')),
                ('phone', models.CharField(max_length=15, verbose_name='\u673a\u623f\u7535\u8bdd')),
                ('codeid', models.CharField(max_length=50, verbose_name='\u5ba2\u6237\u53f7')),
            ],
            options={
                'db_table': 'idcinfo',
                'verbose_name': '\u673a\u623f\u4fe1\u606f\u8868',
                'verbose_name_plural': '\u673a\u623f\u4fe1\u606f\u8868',
            },
        ),
        migrations.CreateModel(
            name='ServerInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=20, verbose_name='\u670d\u52a1\u5668\u578b\u53f7')),
                ('serial', models.CharField(max_length=50, verbose_name='\u5e8f\u5217\u53f7')),
                ('ipaddr', models.CharField(max_length=20, verbose_name='\u670d\u52a1\u5668IP\u5730\u5740')),
                ('CabID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seinfo.CabInfo')),
            ],
            options={
                'db_table': 'serverinfo',
                'verbose_name': '\u670d\u52a1\u5668\u4fe1\u606f\u8868',
                'verbose_name_plural': '\u670d\u52a1\u5668\u4fe1\u606f\u8868',
            },
        ),
        migrations.AddField(
            model_name='cabinfo',
            name='IDCid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seinfo.IDCInfo'),
        ),
    ]
