# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-10 05:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seinfo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cabinfo',
            old_name='locate',
            new_name='cablocate',
        ),
        migrations.RenameField(
            model_name='idcinfo',
            old_name='locate',
            new_name='address',
        ),
    ]
