# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-10 05:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seinfo', '0002_auto_20180810_0541'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cabinfo',
            table='cabinfo',
        ),
    ]
